---
# TODO explain why
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
    
        # ---
        # Rewrite all DNS requests for `*.localhost.identity.team` such that they resolve into the cluster's service for
        # external ingress. This is the Contour-managed, Envoy-backed Service `tanzu-system-ingress/envoy`.
        #
        # As a result, inside the cluster requests for FQDNs `*.localhost.identity.team` resolve the same as external
        # requests, if these FDQNs are managed by Contour-managed APIs `HTTPProxy`, `Ingress`, etc.
        # This renders custom `/etc/hosts` entries redundant which achieved a similar outcome.
        #
        # For example, `GET ci.authservers.localhost.identity.team` takes the same path both inside and outside the
        # cluster.
        #
        rewrite name regex (.*)\.127\.0\.0\.1\.nip\.io ingress-nginx-controller.ingress-nginx.svc.cluster.local
        # ---
    
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
