---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authserver
  name: authserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      serviceAccountName: authserver
      containers:
      - image: springone/authserver
        name: authserver
        ports:
          - containerPort: 8080
            name: authserver
---
apiVersion: v1
kind: Service
metadata:
  name: authserver
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: authserver
  ports:
    - name: authserver
      port: 8080
      targetPort: authserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authserver
  namespace: default
spec:
  rules:
    - host: authserver.127.0.0.1.nip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  name: authserver
