---
apiVersion: v1
kind: Namespace
metadata:
  name: authserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authserver
  namespace: authserver
spec:
  rules:
    - host: authserver.127.0.0.1.nip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  name: authserver

