#@ load("@ytt:data","data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "signing-key-" + data.values.uuid
  namespace: default
stringData:
  key.pem: #@ data.values.key_pem
type: authserver/jwk
