#@  load("@ytt:data", "data")
#@  load("@ytt:struct", "struct")
#@  if "azure" in data.values:
#@     azure = data.values.azure
#@  else:
#@     azure = struct.encode({"client_id": "", "client_secret": "", "issuer_uri": ""})
#@  end
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: authserver
  namespace: demo
  labels:
    name: springone-authserver
    env: "demo"
  annotations:
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
    sso.apps.tanzu.vmware.com/allow-client-namespaces: "demo,apps"
spec:
  tokenSignature:
    signAndVerifyKeyRef:
      name: sample-token-signing-key
    extraVerifyKeyRefs:
      - name: sample-token-verification-key-1
      - name: sample-token-verification-key-2
  identityProviders:
    - name: internal
      internalUnsafe:
        users:
          - username: "user"
            password: "password"
            roles:
              - "message.read"
              - "message.write"
            claims:
              alt_address: "123 Alternate Street"
              email: "jdoe@example.com"
              given_name: "Jane"
              family_name: "Doe"
              preferred_username: "jdoe"
    - name: azure
      openID:
        issuerURI: #@ azure.issuer_uri
        clientID: #@ azure.client_id
        clientSecretRef:
          name: azure-secret
        scopes:
          - openid
          - profile
          - email
        roles:
          fromUpstream:
            claim: "groups"
          filterBy:
            - regex: ".*france.*"
        idToken:
          claims:
            - fromUpstream: "unique_name"
              toClaim: "email"
  replicas: 1

#!~~~~~~~~~~~~~~~~~~~~~~~~~
#! 🔑 Token signing keys
#!~~~~~~~~~~~~~~~~~~~~~~~~~
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: sample-token-signing-key
  namespace: demo
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: sample-token-verification-key-1
  namespace: demo
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: sample-token-verification-key-2
  namespace: demo
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)

#!~~~~~~~~~~~~~~~~~~~~~~~~~
#! 🤫 Secret for identity providers
#!~~~~~~~~~~~~~~~~~~~~~~~~~
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: demo
stringData:
  clientSecret: #@ azure.client_secret

#!~~~~~~~~~~~~~~~~~~~~~~~~~
#! 👀 Make AppSSO discoverable
#!~~~~~~~~~~~~~~~~~~~~~~~~~
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClusterWorkloadRegistrationClass
metadata:
  name: sso-server
spec:
  base:
    spec:
      authServerSelector:
        matchLabels:
          name: springone-authserver
