#! Replace "azure" IDP with in-cluster "dex" IDP
#! This is only applied if "data.values.azure" is missing

#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if "azure" not in data.values:

#! 💡 Remove the "azure" IDP, add the "openid-provider" dex IDP
#@overlay/match by=overlay.subset({"kind": "AuthServer"}), expects=1
---
spec:
  identityProviders:
    #@overlay/match by="name"
    #@overlay/remove
    - name: azure
    #! add dex
    - name: openid-provider
      openID:
        issuerURI: #@ "https://dex." + data.values.domain
        clientID: appsso
        clientSecretRef:
          name: dex-secret
        scopes:
          - openid
          - profile
          - email
          - groups
        roles:
          fromUpstream:
            claim: "groups"

#! 💡 Remove the "azure-secret" secret
#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"azure-secret"}})
#@overlay/remove
---

#! 💡 Add the "dex-secret" Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-secret
  namespace: demo
stringData:
  clientSecret: appsso-secret
#@ end

