---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
  name: demo-client
  namespace: demo
spec:
  authServerSelector:
    matchLabels:
      name: springone-authserver
  redirectURIs:
    - "http://127.0.0.1:8080/login/oauth2/code/demo-client"
  scopes:
    - name: openid
    - name: email
      description: This application will be able to read your e-mail address.
    - name: profile
      description: This application will be able to read your profile information.
  authorizationGrantTypes:
    - authorization_code
    - client_credentials
  clientAuthenticationMethod: client_secret_basic
  requireUserConsent: true
